const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync('app.js','utf8');const c={cleanList:x=>x.map(String).map(x=>x.trim()).filter(Boolean),parseObjectPayload:x=>x&&typeof x==='object'&&!Array.isArray(x)?x:null,firstNonBlankString:(...xs)=>xs.map(x=>String(x||'').trim()).find(Boolean)||''};vm.createContext(c);
for(const name of ['canonicalServiceFormToken','normalizeServiceFormPresetForms','normalizeServiceFormHint','normalizeServiceFormPreset']){const a=src.indexOf('function '+name+'(');vm.runInContext(src.slice(a,src.indexOf('\n}\n',a)+2),c);}
for(const [raw,expected] of [[' v - pc - c - 간주 ','V-PC-C-Int'],['v1a - v2b - c2 - pc1a - b - tags - vl','V1A-V2B-C2-PC1A-B-Tags-VL'],['verse 1 → Pre-Chorus + chorus, interlude > ending','V1-PC-C-Int-Coda'],['1절 - 후렴 - 마지막 절','V1-C-VL'],['V-C-C-Int-C','V-C-C-Int-C'],['custom label - V','custom label-V']]){assert.equal(c.normalizeServiceFormHint(raw),expected);assert.equal(c.normalizeServiceFormHint(expected),expected);const p=c.normalizeServiceFormPreset(raw,raw,'manual');assert.equal(p.hint,expected);assert.equal(p.forms.join('-'),expected);}
assert.equal(c.normalizeServiceFormPresetForms(['v1a',' pc ','간주','C','C']).join('-'),'V1A-PC-Int-C-C');
assert.equal(c.normalizeServiceFormHint('  '),'');assert.match(src,/const formHint = normalizeServiceFormHint\(field.value\)/);assert.match(src,/const formHint = normalizeServiceFormHint\(value.formHint/);
console.log('PASS input/save normalization, numbered parts, repeats, Korean hymn aliases, unknown labels, idempotence');
c.document={};c.compactSearchValue=x=>String(x).replace(/\s+/g,'').toLowerCase();vm.runInContext(fs.readFileSync('mindex.presenter.js','utf8'),c);
for(const token of ['1절','2절','후렴','마지막 절','간주','v1a','pc','c2','b','tags'])assert.equal(JSON.stringify(c.normalizePresenterFormPresetLabel(token)),JSON.stringify(c.normalizePresenterFormPresetLabel(c.canonicalServiceFormToken(token))),token+' must keep playback meaning');
