const assert=require('node:assert/strict');
require('../mindex.worship-week.js');
const {build}=globalThis.MindexWorshipWeek;
const entry=(day,type,aliases=[])=>({source:{service_date:day,service_type_id:type,aliases},candidates:[{raw_title:'곡'}]});
const input=[entry('2026-08-23','sun_3rd',['온세대 찬양예배'])];
const before=JSON.stringify(input);
const result=build(input,[{service_date:'2026-08-28',service_type_id:'fri',service_alias:'문화예배',no_gathering:true}]);
assert.equal(result[0].entries.length,7);
assert.equal(result[0].entries[2].weeklyStatus,'통합예배');
assert.equal(result[0].entries[3].weeklyStatus,'통합예배');
assert.equal(result[0].entries[4].weeklyStatus,'기록 없음');
assert.equal(result[0].entries[6].weeklyStatus,'집회 없음');
assert.equal(result[0].entries[5].source.service_date,'2026-08-26');
assert.equal(JSON.stringify(input),before);
const repeat=build([entry('2026-01-04','youth'),entry('2026-01-18','youth')]);
assert.equal(repeat.length,3);assert.equal(repeat[1].entries[3].weeklyStatus,'기록 없음');
const friday=build([entry('2026-09-04','monthly')]);
assert.equal(friday[0].entries.length,7);assert.equal(friday[0].entries[6].source.service_type_id,'monthly');
assert.equal(build([],[]).length,0);
assert.equal(build([],[{service_date:'2026-09-06',service_type_id:'sun_1st'}]).length,0);
const preserved=build([...input,entry('2026-08-23','children')]);assert.equal(preserved[0].entries[2].candidates.length,1);
const explicit=build([{source:{service_date:'2026-04-05',service_type_id:'youth',weekly_status:'통합예배',weekly_reason:'부활절 연합예배'},candidates:[]}]);
assert.equal(explicit[0].entries[3].weeklyReason,'부활절 연합예배');
console.log('PASS weekly slots, dates, gaps, explicit absence, combined worship, actual record precedence, immutability');
