"""Service order templates for Mindex Service.

These are structural templates, not weekly content seeds. They describe the
usual order, flexible spots, and repeatable components for each service type.
"""


def response_section_template():
    return {
        "label": "결단",
        "name": "Commitment",
        "phase": "Response",
        "required": False,
        "flex": True,
        "sectionKey": "response_song",
        "elements": [
            {"label": "결단찬양", "name": "Song of Response", "elementType": "praise", "orderSheet": {"order": "결단찬양", "group": "praise"}},
            {"label": "결단기도", "name": "Prayer of Commitment", "elementType": "title_person", "orderSheet": {"order": "결단기도"}},
        ],
    }


SERVICE_ORDER_TEMPLATES = {
    "sunday-main": [
        {"label": "준비", "name": "Preparation", "phase": "Gathering", "required": False, "flex": True},
        {"label": "사도신경", "name": "Apostles' Creed", "phase": "Gathering", "required": True, "flex": False},
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": False, "flex": True, "repeatable": True, "notes": "3부/찬양예배 등에서 앞 찬양이 들어감"},
        {"label": "참회기도", "name": "Prayer of Confession", "phase": "Gathering", "required": False, "flex": True},
        {"label": "기도", "name": "Opening Prayer", "phase": "Gathering", "required": False, "flex": True},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False},
        {"label": "특송", "name": "Special Music", "phase": "Word", "required": False, "flex": True},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False},
        {"label": "결단기도", "name": "Prayer of Commitment", "phase": "Response", "required": False, "flex": True},
        {"label": "봉헌", "name": "Offering", "phase": "Response", "required": True, "flex": False},
        {"label": "봉헌기도", "name": "Prayer of Dedication", "phase": "Response", "required": True, "flex": False},
        {"label": "교회소식", "name": "Announcements", "phase": "Sending", "required": True, "flex": False},
        {"label": "송영", "name": "Doxology", "phase": "Sending", "required": True, "flex": False},
        {"label": "축도", "name": "Benediction", "phase": "Sending", "required": True, "flex": False},
    ],
    "sunday-afternoon": [
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": False, "flex": True, "repeatable": True, "default_count": 4},
        {"label": "묵도", "name": "Silent Prayer", "phase": "Gathering", "required": True, "flex": False},
        {"label": "찬송", "name": "Hymn", "phase": "Gathering", "required": True, "flex": False},
        {"label": "기도", "name": "Opening Prayer", "phase": "Gathering", "required": True, "flex": False},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False},
        {"label": "결단기도", "name": "Prayer of Commitment", "phase": "Response", "required": False, "flex": True},
        {"label": "교회소식", "name": "Announcements", "phase": "Sending", "required": True, "flex": False},
        {"label": "송영", "name": "Doxology", "phase": "Sending", "required": True, "flex": False},
        {"label": "축도", "name": "Benediction", "phase": "Sending", "required": True, "flex": False},
    ],
    "wednesday": [
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": True, "flex": True, "repeatable": True, "default_count": 4},
        {"label": "기도", "name": "Opening Prayer", "phase": "Gathering", "required": True, "flex": False},
        {"label": "교회소식", "name": "Announcements", "phase": "Gathering", "required": False, "flex": True},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False},
        response_section_template(),
        {"label": "축도", "name": "Benediction", "phase": "Sending", "required": True, "flex": False},
    ],
    "friday": [
        {"label": "준비", "name": "Preparation", "phase": "Gathering", "required": False, "flex": True},
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": True, "flex": True, "repeatable": True, "default_count": 5},
        {"label": "기도", "name": "Opening Prayer", "phase": "Gathering", "required": True, "flex": False},
        {"label": "특송", "name": "Special Music", "phase": "Gathering", "required": False, "flex": True},
        {"label": "교회소식", "name": "Announcements", "phase": "Gathering", "required": False, "flex": True},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False},
        response_section_template(),
        {"label": "기도회", "name": "Prayer Meeting", "phase": "Response", "required": True, "flex": True},
        {"label": "찬양", "name": "Prayer Praise", "phase": "Response", "required": False, "flex": True, "repeatable": True, "default_count": 3},
        {"label": "통성기도", "name": "Corporate Prayer", "phase": "Response", "required": True, "flex": True},
        {"label": "자율기도", "name": "Open Prayer", "phase": "Sending", "required": True, "flex": False},
    ],
    "monthly": [
        {"label": "준비", "name": "Preparation", "phase": "Gathering", "required": False, "flex": True, "sectionKey": "ready", "elementType": "video"},
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": True, "flex": True, "repeatable": True, "sectionKey": "praise", "elements": [
            {"label": "찬양", "name": "Praise 1", "elementType": "praise"},
            {"label": "찬양", "name": "Praise 2", "elementType": "praise"},
            {"label": "찬양", "name": "Praise 3", "elementType": "praise"},
            {"label": "찬양", "name": "Praise 4", "elementType": "praise"},
            {"label": "찬양", "name": "Praise 5", "elementType": "praise"},
        ]},
        {"label": "기도", "name": "Opening Prayer", "phase": "Gathering", "required": True, "flex": False, "sectionKey": "prayer", "elementType": "title_person"},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False, "sectionKey": "scripture_reading", "elementType": "scripture_reading"},
        {"label": "특송", "name": "Special Music", "phase": "Word", "required": False, "flex": True, "sectionKey": "special_song", "elementType": "title_person"},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False, "sectionKey": "sermon", "elementType": "body"},
        response_section_template(),
        {"label": "월삭기도", "name": "Monthly Prayer", "phase": "Response", "required": True, "flex": True, "sectionKey": "monthly_prayer", "elements": [
            {"label": "월삭기도", "name": "Prayer 1", "elementType": "title_person"},
            {"label": "월삭기도", "name": "Prayer 2", "elementType": "title_person"},
            {"label": "찬양", "name": "Prayer Praise", "elementType": "praise"},
            {"label": "월삭기도", "name": "Prayer 3", "elementType": "title_person"},
            {"label": "월삭기도", "name": "Prayer 4", "elementType": "title_person"},
        ]},
        {"label": "봉헌", "name": "Offering", "phase": "Response", "required": True, "flex": False, "sectionKey": "offering", "elements": [
            {"label": "봉헌", "name": "Offering Song", "elementType": "praise", "default_text": "이런 교회 되게 하소서", "formHint": "V-C", "formPreset": {"forms": ["V", "C"], "strength": "suggested"}, "defaultStrength": "suggested"},
            {"label": "봉헌기도", "name": "Prayer of Dedication", "elementType": "title_person"},
        ]},
        {"label": "교회소식", "name": "Announcements", "phase": "Sending", "required": True, "flex": False, "sectionKey": "announcements", "elementType": "plain_text"},
        {"label": "찬양", "name": "Praise", "phase": "Sending", "required": True, "flex": False, "sectionKey": "closing_song", "elementType": "praise", "default_text": "여기에 모인 우리", "formHint": "V1-C-C", "formPreset": {"forms": ["V1", "C", "C"], "strength": "default"}, "defaultStrength": "default"},
        {"label": "축도", "name": "Benediction", "phase": "Sending", "required": True, "flex": False, "sectionKey": "benediction", "elementType": "title_person"},
    ],
    "dawn": [
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": True, "flex": True, "repeatable": True, "default_count": 3},
        {"label": "기도", "name": "Opening Prayer", "phase": "Gathering", "required": False, "flex": True},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False},
        {"label": "기도", "name": "Prayer", "phase": "Response", "required": True, "flex": True},
    ],
    "omer": [
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": True, "flex": True, "repeatable": True, "default_count": 4},
        {"label": "기도", "name": "Prayer", "phase": "Response", "required": True, "flex": True, "repeatable": True, "default_count": 2},
        {"label": "특송", "name": "Special Music", "phase": "Response", "required": False, "flex": True},
        {"label": "결단", "name": "Commitment", "phase": "Response", "required": False, "flex": True},
    ],
    "special": [],
    "children": [
        {"label": "준비", "name": "Preparation", "phase": "Gathering", "required": False, "flex": True},
        {"label": "사도신경", "name": "Apostles' Creed", "phase": "Gathering", "required": True, "flex": False},
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": True, "flex": True, "repeatable": True, "default_count": 4},
        {"label": "예배의 부름", "name": "Opening", "phase": "Gathering", "required": False, "flex": True},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False},
        {"label": "결단기도", "name": "Prayer of Commitment", "phase": "Response", "required": False, "flex": True},
        {"label": "봉헌", "name": "Offering", "phase": "Response", "required": True, "flex": False},
        {"label": "봉헌찬양", "name": "Offertory Song", "phase": "Response", "required": True, "flex": False},
        {"label": "봉헌기도", "name": "Prayer of Dedication", "phase": "Response", "required": True, "flex": False},
        {"label": "나래파송", "name": "Sending", "phase": "Sending", "required": True, "flex": False},
        {"label": "주기도문", "name": "Lord's Prayer", "phase": "Sending", "required": True, "flex": False},
        {"label": "광고", "name": "Announcements", "phase": "Sending", "required": True, "flex": False},
        {"label": "교제", "name": "Fellowship", "phase": "Sending", "required": False, "flex": True},
    ],
    "youth": [
        {"label": "준비", "name": "Preparation", "phase": "Gathering", "required": False, "flex": True},
        {"label": "사도신경", "name": "Apostles' Creed", "phase": "Gathering", "required": True, "flex": False},
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": True, "flex": True, "repeatable": True, "default_count": 3},
        {"label": "통성기도", "name": "Corporate Prayer", "phase": "Gathering", "required": False, "flex": True},
        {"label": "대표기도", "name": "Opening Prayer", "phase": "Gathering", "required": True, "flex": False},
        {"label": "봉헌", "name": "Offering", "phase": "Response", "required": True, "flex": False},
        {"label": "봉헌찬양", "name": "Offertory Song", "phase": "Response", "required": True, "flex": False},
        {"label": "봉헌기도", "name": "Prayer of Dedication", "phase": "Response", "required": True, "flex": False},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False},
        response_section_template(),
        {"label": "주기도문", "name": "Lord's Prayer", "phase": "Sending", "required": True, "flex": False},
        {"label": "광고", "name": "Announcements", "phase": "Sending", "required": True, "flex": False},
        {"label": "교제", "name": "Fellowship", "phase": "Sending", "required": False, "flex": True},
    ],
    "young-adult": [
        {"label": "준비", "name": "Preparation", "phase": "Gathering", "required": False, "flex": True},
        {"label": "사도신경", "name": "Apostles' Creed", "phase": "Gathering", "required": True, "flex": False},
        {"label": "대표기도", "name": "Opening Prayer", "phase": "Gathering", "required": True, "flex": False},
        {"label": "찬양", "name": "Praise", "phase": "Gathering", "required": True, "flex": True, "repeatable": True, "default_count": 4},
        {"label": "통성기도", "name": "Corporate Prayer", "phase": "Gathering", "required": False, "flex": True},
        {"label": "성경봉독", "name": "Scripture Reading", "phase": "Word", "required": True, "flex": False},
        {"label": "설교", "name": "Sermon", "phase": "Word", "required": True, "flex": False},
        response_section_template(),
        {"label": "봉헌", "name": "Offering", "phase": "Response", "required": True, "flex": False},
        {"label": "봉헌찬양", "name": "Offertory Song", "phase": "Response", "required": True, "flex": False},
        {"label": "봉헌기도", "name": "Prayer of Dedication", "phase": "Response", "required": True, "flex": False},
        {"label": "광고", "name": "Announcements", "phase": "Sending", "required": True, "flex": False},
        {"label": "찬양", "name": "Praise", "phase": "Sending", "required": True, "flex": False},
        {"label": "축도", "name": "Benediction", "phase": "Sending", "required": True, "flex": False},
        {"label": "교제", "name": "Fellowship", "phase": "Sending", "required": False, "flex": True},
    ],
}

SERVICE_ORDER_TEMPLATES.setdefault("sunday-first", SERVICE_ORDER_TEMPLATES["sunday-main"])
SERVICE_ORDER_TEMPLATES.setdefault("sunday-second", SERVICE_ORDER_TEMPLATES["sunday-main"])
